// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package driver

import (
	"fmt"

	"google.golang.org/protobuf/proto"
)

// PolicyClass denotes whether a policy represents a Destination, Source, or Transformation.
type PolicyClass int

const (
	PolicyClassDestination PolicyClass = iota
	PolicyClassSource
	PolicyClassTransformation
)

func (c PolicyClass) String() string {
	switch c {
	case PolicyClassDestination:
		return "destination"
	case PolicyClassSource:
		return "source"
	case PolicyClassTransformation:
		return "transformation"
	default:
		return fmt.Sprintf("unknown(%d)", c)
	}
}

// PipelineConfig defines the receivers, processors, and exporters for a single signal pipeline.
type PipelineConfig struct {
	Receivers  []string `mapstructure:"receivers"`
	Processors []string `mapstructure:"processors"`
	Exporters  []string `mapstructure:"exporters"`
}

// ConfigFragment represents the collector configuration fragment generated by a policy driver.
type ConfigFragment struct {
	Receivers   map[string]any
	Processors  map[string]any
	Exporters   map[string]any
	Extensions  map[string]any
	Pipelines   map[string]PipelineConfig
	ServiceExts []string
}

// NewConfigFragment returns an initialized ConfigFragment.
func NewConfigFragment() *ConfigFragment {
	return &ConfigFragment{
		Receivers:  make(map[string]any),
		Processors: make(map[string]any),
		Exporters:  make(map[string]any),
		Extensions: make(map[string]any),
		Pipelines:  make(map[string]PipelineConfig),
	}
}

// CompilationContext contains runtime contextual metadata available during configuration compilation.
type CompilationContext struct {
	PolicyID       string
	FleetID        string
	CollectorID    string
	ResolvedTokens map[string]string
}

// PolicyDriver defines the interface that all policy schema translators must implement.
type PolicyDriver interface {
	TypeURL() string
	Class() PolicyClass
	Validate(policy proto.Message) error
	GenerateConfig(policy proto.Message, ctx *CompilationContext) (*ConfigFragment, error)
}
